version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maratona-peer-to-peer
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge